export const keyboardLayout = [
  // Function keys
  [
    { label: "esc", width: 1.25, isSpecial: true },
    // { label: "", width: 1 },
    { label: "F1", width: 1, isSpecial: true },
    { label: "F2", width: 1, isSpecial: true },
    { label: "F3", width: 1, isSpecial: true },
    { label: "F4", width: 1, isSpecial: true },
    { label: "F5", width: 1, isSpecial: true },
    { label: "F6", width: 1, isSpecial: true },
    { label: "F7", width: 1, isSpecial: true },
    { label: "F8", width: 1, isSpecial: true },
    { label: "F9", width: 1, isSpecial: true },
    { label: "F10", width: 1, isSpecial: true },
    { label: "F11", width: 1, isSpecial: true },
    { label: "F12", width: 1, isSpecial: true },
    { label: "", width: 1 },
  ],
  // Number keys
  [
    { label: "`", width: 1 },
    { label: "1", width: 1 },
    { label: "2", width: 1 },
    { label: "3", width: 1 },
    { label: "4", width: 1 },
    { label: "5", width: 1 },
    { label: "6", width: 1 },
    { label: "7", width: 1 },
    { label: "8", width: 1 },
    { label: "9", width: 1 },
    { label: "0", width: 1 },
    { label: "-", width: 1 },
    { label: "=", width: 1 },
    { label: "delete", width: 1.25, isSpecial: true },
  ],
  // QWERTY
  [
    { label: "tab", width: 1.25, isSpecial: true },
    { label: "Q", width: 1 },
    { label: "W", width: 1 },
    { label: "E", width: 1 },
    { label: "R", width: 1 },
    { label: "T", width: 1 },
    { label: "Y", width: 1 },
    { label: "U", width: 1 },
    { label: "I", width: 1 },
    { label: "O", width: 1 },
    { label: "P", width: 1 },
    { label: "[", width: 1 },
    { label: "]", width: 1 },
    { label: "\\", width: 1 },
  ],
  // ASDF
  [
    { label: "⇪", width: 1.5, isSpecial: true },
    { label: "A", width: 1 },
    { label: "S", width: 1 },
    { label: "D", width: 1 },
    { label: "F", width: 1 },
    { label: "G", width: 1 },
    { label: "H", width: 1 },
    { label: "J", width: 1 },
    { label: "K", width: 1 },
    { label: "L", width: 1 },
    { label: ";", width: 1 },
    { label: "'", width: 1 },
    { label: "return", width: 1.75, isSpecial: true },
  ],
  // ZXCV
  [
    { label: "shift", width: 1.25, isSpecial: true, isLeft: true },
    { label: "Z", width: 1 },
    { label: "X", width: 1 },
    { label: "C", width: 1 },
    { label: "V", width: 1 },
    { label: "B", width: 1 },
    { label: "N", width: 1 },
    { label: "M", width: 1 },
    { label: ",", width: 1 },
    { label: ".", width: 1 },
    { label: "/", width: 1 },
    { label: "shift", width: 3, isSpecial: true },
  ],
  // Bottom row
  [
    { label: "fn", width: 1, isSpecial: true },
    { label: "control", width: 1, isSpecial: true },
    { label: "⌥", width: 1, isSpecial: true, isLeft: true },
    { label: "⌘", width: 1.5, isLeft: true, isSpecial: true },
    { label: "space", width: 3.5 },
    { label: "⌘", width: 1.5, isLeft: false, isSpecial: true },
    { label: "⌥", width: 1, isSpecial: true },
    { label: "◀", width: 1, isSpecial: true },
    { label: "▲", width: 1, isSpecial: true },
    { label: "▼", width: 1, isSpecial: true },
    { label: "►", width: 1, isSpecial: true },
  ],
];
